# Generated by Django 4.2.2 on 2023-07-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutstore', '0004_cartitem_is_active_alter_cartitem_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
